# Generated by Django 4.2.20 on 2025-03-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(unique=True)),
                ('sitemap', models.TextField()),
                ('insights', models.TextField()),
            ],
        ),
    ]
